apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data: 
  MONGO_ROOT_USERNAME: YWRtaW4= #value disi hraus base64 nanti nya akan di decrypt
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==