apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  labels:
    app: backend
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30007 # ini agar port service nya tetap
  selector:
    app: backend