apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service-ui
  labels:
    app: frontend
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    nodePort: 30001
  selector:
    app: frontend